In [1]:
import caffe
import cv2
import preprocess
from os import listdir
from os.path import isfile, join
import time
import numpy as np

In [2]:
model = 'caffe_files/caffe_model.prototxt'
weights = 'caffe_files/caffe_weight.caffemodel'

In [3]:
net = caffe.Net(model, weights, caffe.TEST)

In [9]:
cv2.imread(files[0])

array([[[ 0,  1,  0],
        [ 0,  1,  0],
        [ 0,  1,  0],
        ...,
        [ 0,  0,  1],
        [ 0,  0,  1],
        [ 0,  0,  1]],

       [[ 0,  1,  0],
        [ 0,  1,  0],
        [ 0,  1,  0],
        ...,
        [ 2,  4,  5],
        [ 0,  0,  1],
        [ 0,  0,  1]],

       [[ 0,  1,  0],
        [ 0,  1,  0],
        [ 0,  1,  0],
        ...,
        [ 0,  0,  0],
        [ 4,  2,  2],
        [ 2,  2,  2]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0, 20,  1],
        [ 0, 19,  0],
        [ 0, 19,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0, 21,  2],
        [ 0, 19,  0],
        [ 0, 19,  0]],

       [[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        ...,
        [ 0, 20,  1],
        [ 0, 20,  0],
        [ 0, 20,  0]]], dtype=uint8)

In [14]:
net.blobs['data'] = cv2.imread(files[0])
net.forward()

{'dense_4': array([[-0.05869625]], dtype=float32)}

In [53]:
root = "../AutoCar/records_good/"

start_time = time.time()
files = [ join(root, f) for f in listdir(root) if isfile(join(root, f))]
imgs = [ img for img in map(cv2.imread, files) ]
imgs = [ img for img in map(preprocess.preprocess, imgs)]
print("--- %s seconds ---" % (time.time() - start_time))

/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):


--- 8.167327404022217 seconds ---


In [41]:
# net.forward(img)['dense_4']

start_time = time.time()
to_pred = np.array(imgs)
net.blobs['data'] = to_pred
preds = [net.forward() for i in range(to_pred.shape[0])]
print("--- %s seconds ---" % (time.time() - start_time))

--- 52.52134704589844 seconds ---


In [4]:
import md

model = md.build_model()
model.load_weights('models/model-0,0YUV.h5')

Using TensorFlow backend.
/home/cai/scia_project/car_repo/md.py:20: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(24, (5, 5), strides=(2, 2), activation="elu")`
  model.add(Conv2D(24, (5, 5), activation='elu', subsample=(2, 2)))
/home/cai/scia_project/car_repo/md.py:21: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(36, (5, 5), strides=(2, 2), activation="elu")`
  model.add(Conv2D(36, (5, 5), activation='elu', subsample=(2, 2)))
/home/cai/scia_project/car_repo/md.py:22: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(48, (5, 5), strides=(2, 2), activation="elu")`
  model.add(Conv2D(48, (5, 5), activation='elu', subsample=(2, 2)))


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lambda_1 (Lambda)            (None, 66, 200, 3)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 31, 98, 24)        1824      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 47, 36)        21636     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 5, 22, 48)         43248     
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 3, 20, 64)         27712     
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 1, 18, 64)         36928     
_________________________________________________________________
dropout_1 (Dropout)          (None, 1, 18, 64)         0         
__________

In [43]:
start_time = time.time()
keras_preds = model.predict(np.array(imgs))
print("--- %s seconds ---" % (time.time() - start_time))

--- 32.801634550094604 seconds ---


In [19]:
preds

{'dense_4': array([[-0.05869625]], dtype=float32)}

In [328]:
start_time = time.time()
net.forward()
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.016558170318603516 seconds ---


In [298]:
start_time = time.time()
model.predict(np.array([imgs[0]]))
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.024680137634277344 seconds ---


In [20]:
# load images
img_1 = cv2.imread('example.jpg')
img_2 = cv2.imread('example2.jpg')
img_1 = preprocess.preprocess(img_1)
img_2 = preprocess.preprocess(img_2)

/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/local/lib/python3.5/dist-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):


In [35]:
net.blobs['data'] = img_1 / 127.5 - 1.0
net.forward()

{'dense_4': array([[-0.05869625]], dtype=float32)}

In [37]:
model.predict(np.array([img_1]))

array([[-0.39312506]], dtype=float32)

In [44]:
%timeit 1000000
#net.blobs['data'] = img_2 / 127.5 - 1.0
net.forward()

54.7 ns ± 1.39 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


{'dense_4': array([[-0.05869625]], dtype=float32)}

In [43]:
%timeit 1000000
model.predict(np.array([img_2]))

54.6 ns ± 1.27 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


array([[-0.67522526]], dtype=float32)